CREATE TABLE products (
    sku VARCHAR(20) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    type VARCHAR(20) NOT NULL
);

CREATE TABLE books (
    sku VARCHAR(20) NOT NULL PRIMARY KEY,
    weight DECIMAL(10, 3) NOT NULL,
    FOREIGN KEY (sku) REFERENCES products (sku) ON DELETE CASCADE
);

CREATE TABLE dvds (
    sku VARCHAR(20) NOT NULL PRIMARY KEY,
    size VARCHAR(20) NOT NULL,
    FOREIGN KEY (sku) REFERENCES products (sku) ON DELETE CASCADE
);
CREATE TABLE furnitures (
    sku VARCHAR(20) NOT NULL PRIMARY KEY,
    length VARCHAR(20) NOT NULL,
    width VARCHAR(20) NOT NULL,
    height VARCHAR(20) NOT NULL,
    FOREIGN KEY (sku) REFERENCES products (sku) ON DELETE CASCADE
);